### ISSUE TITLE
Valid and updated documentation

### ISSUE THREAD

**Issue by xMagiciaNx** [serenity-bdd/serenity-jira#102]
Hello. I see that currently may be a zapi support. Is there any well documented resource, to find a way out? Thanks a million.

**Comment by wakaleo** [comment]
Zephyr is not currently supported, but if you would like to update/maintain the code and docs you are welcome to make a pull request.

**Comment by xMagiciaNx** [comment]
Nice to let me know. Absolutely. If I implement the feature, I will make the pull request. Thank you.
