### ISSUE TITLE
JIRACustomFieldsRequirementsProvider cannot be loaded

### ISSUE THREAD

**Issue by dmitriy-grablyov** [serenity-bdd/serenity-jira#36]
Hi all,
It seems that for now it is not possible to use JIRACustomFieldsRequirementsProvider

The class itself is located at net.serenitybdd.plugins.jira.requirements
However net.thucydides.core.statistics.service.TagProvider in META-INF/services declares that it should be taken from net.thucydides.plugins.jira.requirements (thucydides is not changed to serenitybdd) and hence test execution fails with java.util.ServiceConfigurationError: net.thucydides.core.statistics.service.TagProvider: Provider net.thucydides.plugins.jira.requirements.JIRACustomFieldsRequirementsProvider not found

**Comment by YamStranger** [comment]
@dmitriy-grablyov Thanks!

**Comment by YamStranger** [comment]
@dmitriy-grablyov it is fixed, and will be included in next release.
