### ISSUE TITLE
can't build when using 1.1.1-rc.2

### ISSUE THREAD

**Issue by c-mu** [serenity-bdd/serenity-jira#8]
I have upgraded from 1.0.1 to 1.1.1-rc.2 to test [serenity-core #136](https://github.com/serenity-bdd/serenity-core/issues/136) and had the following findings:
* groupId is set to _repo_ instead of _net.serenity-bdd_
* When I put serenity-jira-requirements-provider on the classpath, gradle complains that it can't find serenity-jira-requirements-provider.jar (note the missing version number in the file name)

First one is an annoyance, but may have been done so on purpose. Second one is blocking (re-)testing.

Any thoughts?

**Comment by cliviu** [comment]
hi, dependency downloading works ok for me :
```xml
    testCompile "repo:serenity-jira-plugin:1.1.1-rc.2"
    testCompile "repo:serenity-jira-requirements-provider:1.1.1-rc.2"
```
sure, repo should be replaced with net.serenity-bdd :-)

**Comment by cliviu** [comment]
hi, the new maven products are available:

```xml
    testCompile "net.serenity-bdd:serenity-jira-plugin:1.1.1-rc.3"
    testCompile "net.serenity-bdd:serenity-jira-requirements-provider:1.1.1-rc.3"
```

**Comment by c-mu** [comment]
hi, I can now again successfully build when including these dependencies.
