### ISSUE TITLE
thucydides.public.url property considered instead of serenity.public.url 

### ISSUE THREAD

**Issue by maxipic** [serenity-bdd/serenity-jira#9]
I found that, while trying to set up the two-way integration with JIRA using the latest version of the Serenity-Jira plugin available on MVNRepository (from Jan 2016, here http://mvnrepository.com/artifact/net.serenity-bdd/serenity-jira-plugin), the property 'serenity.public.url' does not work as expected. Instead, 'thucydides.public.url' does work fine and JIRA get the issue updated despite the documentation mentions 'serenity.public.url'.

Digging into the source code I found that the class _net.serenitybdd.plugins.jira.JiraListener_ still uses the  Enum value THUCYDIDES_PUBLIC_URL from the net.thucydides.core.ThucydidesSystemProperty Enum (which is part of the Core package and contains many 'serenity' to 'thucydides' translate methods)

I couldn't debug it further, but my gut feeling is that something might not be right in line 93 of _net.serenitybdd.plugins.jira.JiraListener_:

    String reportUrl = environmentVariables.getProperty(ThucydidesSystemProperty.THUCYDIDES_PUBLIC_URL.getPropertyName());

**Comment by YamStranger** [comment]
@maxipic Thanks for this issue!!

**Comment by YamStranger** [comment]
Hello @maxipic 
It seems that this issue fixed by @cliviu, can you check it? (v1.1.2-rc.1)

If all work as you expect - please close this issue. 
Thanks a lot!!

**Comment by YamStranger** [comment]
According to history this issue should be already closed, so I will close this ticket
